/**
 * LeetCode Explainer Animation Library
 * Main entry point for all animation-related functionality
 */

// Core canvas system
export {
  CanvasRenderer,
  BaseVisualization
} from './canvas-renderer.js';

// Algorithm detection and code synchronization
export {
  AlgorithmDetector,
  CodeSynchronizer
} from './algorithm-detector.js';

// LLM-powered animation generation
export {
  LLMAnimationGenerator
} from './llm-generator.js';

// Canvas visualization elements
export {
  AnimationRenderer,
  BaseElement,
  ArrayElement,
  PointerElement,
  HighlightElement,
  TextElement,
  BarsElement,
  GridElement,
  GraphElement
} from './visualization-elements.js';

// Algorithm-specific visualizations (now generated by LLM)
// These are no longer exported as they're dynamically created
